"""
ComfyUI Dynamic TOML Selector Node
"""

from .toml_selector_node import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
from .toml_selector_ultra import NODE_CLASS_MAPPINGS_ULTRA, NODE_DISPLAY_NAME_MAPPINGS_ULTRA
from .toml_selector_fixed import NODE_CLASS_MAPPINGS_FIXED, NODE_DISPLAY_NAME_MAPPINGS_FIXED

# Merge mappings
NODE_CLASS_MAPPINGS = {**NODE_CLASS_MAPPINGS, **NODE_CLASS_MAPPINGS_ULTRA, **NODE_CLASS_MAPPINGS_FIXED}
NODE_DISPLAY_NAME_MAPPINGS = {**NODE_DISPLAY_NAME_MAPPINGS, **NODE_DISPLAY_NAME_MAPPINGS_ULTRA, **NODE_DISPLAY_NAME_MAPPINGS_FIXED}

WEB_DIRECTORY = "./js"

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS', 'WEB_DIRECTORY']