# ComfyUI Configuration Examples

[style_photorealistic]
prompt_style = "photorealistic, high detail, 8k, professional photography"
negative_prompt = "cartoon, anime, illustration, painting, drawing"
cfg_scale = 7.5
steps = 30
sampler = "dpmpp_2m"
scheduler = "karras"
denoise = 1.0

[style_anime]
prompt_style = "anime style, cel shaded, vibrant colors, studio quality"
negative_prompt = "realistic, photo, 3d render, ugly, deformed"
cfg_scale = 12.0
steps = 25
sampler = "euler_ancestral"
scheduler = "normal"
denoise = 1.0

[style_oil_painting]
prompt_style = "oil painting, classical art, brush strokes, museum quality"
negative_prompt = "photo, digital art, 3d, modern, contemporary"
cfg_scale = 9.0
steps = 40
sampler = "ddim"
scheduler = "simple"
denoise = 0.85

[quality_draft]
width = 512
height = 512
batch_size = 1
seed = -1
clip_skip = 1

[quality_standard]
width = 768
height = 768
batch_size = 1
seed = -1
clip_skip = 2

[quality_high]
width = 1024
height = 1024
batch_size = 1
seed = -1
clip_skip = 2

[model_sd15]
model_name = "stable-diffusion-v1-5"
vae_name = "vae-ft-mse-840000"
upscaler = "4x-UltraSharp"
clip_strength = 1.0

[model_sdxl]
model_name = "stable-diffusion-xl-base-1.0"
vae_name = "sdxl-vae"
upscaler = "4x_NMKD-Superscale"
clip_strength = 1.0