# Example configuration with more complex data

[character_mario]
name = "Mario"
power = 10
speed = 7.5
jump_height = "high"
color = "red"
has_powerup = true

[character_luigi]
name = "Luigi"
power = 8
speed = 8.0
jump_height = "very high"
color = "green"
has_powerup = false
special_ability = "flutter jump"

[level_1]
difficulty = "easy"
enemies = 5
time_limit = 300
has_boss = false

[level_2]
difficulty = "medium"
enemies = 12
time_limit = 240
has_boss = true
boss_name = "Bowser"
secret_exits = 2

[settings]
resolution = "1920x1080"
fullscreen = true
volume = 75
language = "pt-BR"